name: Publish

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push

    permissions:
      contents: read
      packages: write

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build
      run: docker build . --tag ghcr.io/${{github.actor}}/eco-stream-ui:latest
    
    - name: Push
      run: docker push ghcr.io/${{github.actor}}/eco-stream-ui:latest
